with open("prueba60.plot", "w") as f:
    print("set terminal png truecolor", file = f)
    print("set output 'imgen60.png'", file = f)
    print("set key off", file = f)
    print("set title 'Nodos'", file = f)
    print("set xlabel 'Probabilidad'", file = f)
    print("set ylabel 'Distancia promedio normalizada (azul)'", file = f)
    print("set y2label 'Densidad promedio (rojo)'", file = f)
    print("set style line 1 lc rgb '#0000ff' lt 1 lw 1", file = f)
    print("set style line 2 lc rgb '#ff0000' lt 1 lw 1", file = f)
    print("plot[0:0.5][0:1] 'Resultadods60.csv' using 1:2 w lines ls 1, 'Resultadocluster60.csv' using 1:3 w lines ls 2", file = f)
