library(readr)
library(prob)
library(plyr)
library(graphics)
library(gtools)
Tiempos <- as.data.frame(t(read.csv("Tiempo60.csv", header=FALSE)))
T90<-as.data.frame(t(read.csv("Tiempo90.csv", header=FALSE)))
T120<-as.data.frame(t(read.csv("Tiempo1.csv", header=FALSE)))
T150<-as.data.frame(t(read.csv("Tiempo150.csv", header=FALSE)))
TTotales<-t(smartbind(Tiempos, T90, T120, T150,fill=0))
shapiro.test(TTotales)#no normales
pdf("TiempovsN.pdf")
boxplot(TTotales, main="Tiempo versus Cantidad de nodos", xlab=c("Número de nodos"), ylab=c("Tiempo (segundos)"), varwidht=TRUE, notch=FALSE, plot=TRUE)
par(new=TRUE, pty="m", xaxt="n", yaxt="n")
plot(seq(1:4)^3, type="l" , xlab="", ylab="", col="blue", lwd=2)
legend("topleft",col=c("Blue"), legend =c("Función Cúbica"), lwd=3, bty = "n")
graphics.off()