library(readr)
library(prob)
library(plyr)
library(graphics)
library(gtools)
Tiempos <- as.data.frame(t(read.csv("Tiempo1.csv", header=FALSE)))
Tiempos1<-as.data.frame(t(read.csv("tiempov0.csv", header=FALSE)))
Tiempos2<-as.data.frame(t(read.csv("tiempov1.csv", header=FALSE)))
Tiempos3<-as.data.frame(t(read.csv("tiempov2.csv", header=FALSE)))
Tiempos4<-as.data.frame(t(read.csv("tiempov3.csv", header=FALSE)))
TiempoT<-rbind(Tiempos,Tiempos1,Tiempos2,Tiempos3,Tiempos4)
colnames(TiempoT) <- c(5:19)
shapiro.test(t(TiempoT)) #No son normales
pdf("TFord.pdf")
boxplot(TiempoT, main="Tiempo versus número de nodos", xlab=c("Número de nodos"), ylab=c("Tiempo (segundos)"), plot=TRUE)
par(new=TRUE, pty="s", xaxt="n", yaxt="n", xaxs="i")
plot(seq(0.01,0.15,length=15)^3, type="l" , xlab="", ylab="", col="blue", lwd=2)
legend("topleft",col=c("Blue"), legend =c("Función cúbica"), lwd=3, bty = "n")

Tiempo2 <- as.data.frame(t(read.csv("Tiempo2.csv", header=FALSE)))
Tiempos21<-as.data.frame(t(read.csv("tiempo2v0.csv", header=FALSE)))
Tiempos22<-as.data.frame(t(read.csv("tiempo2v1.csv", header=FALSE)))
Tiempos23<-as.data.frame(t(read.csv("tiempo2v2.csv", header=FALSE)))
Tiempos24<-as.data.frame(t(read.csv("tiempo2v3.csv", header=FALSE)))
TiempoT2<-rbind(Tiempos2,Tiempos21,Tiempos22,Tiempos23,Tiempos24)
colnames(TiempoT2) <- c(5:19)
shapiro.test(t(TiempoT2)) #No son normales
pdf("T2Ford.pdf")
boxplot(TiempoT2, main="Tiempo versus número de nodos", xlab=c("Número de nodos"), ylab=c("Tiempo (segundos)"), plot=TRUE)
par(new=TRUE, pty="s", xaxt="n", yaxt="n", xaxs="i")
plot(expm1(seq(0.01,0.15,length=15)^3), type="l" , xlab="", ylab="", col="red", lwd=2)
legend("topleft",col=c("Red"), legend =c("Función cúbica"), lwd=3, bty = "n")

Flujo <- as.data.frame(t(read.csv("Ford-Fulkerson1.csv", header=FALSE)))
Flujo1<-as.data.frame(t(read.csv("Ford-Fulkersonv0.csv", header=FALSE)))
Flujo2<-as.data.frame(t(read.csv("Ford-Fulkersonv1.csv", header=FALSE)))
Flujo3<-as.data.frame(t(read.csv("Ford-Fulkersonv2.csv", header=FALSE)))
Flujo4<-as.data.frame(t(read.csv("Ford-Fulkersonv3.csv", header=FALSE)))
FlujoT<-rbind(Flujo,Flujo1,Flujo2,Flujo3,Flujo4)
colnames(FlujoT) <- c(5:19)
shapiro.test(t(FlujoT)) #Son normales ya que vienen de datos generados normalmente
pdf("FlujoFord.pdf")
boxplot(FlujoT, main="Flujo versus número de nodos", xlab=c("Número de nodos"), ylab=c("Flujo"), plot=TRUE)
par(new=TRUE, pty="s", xaxt="n", yaxt="n", xaxs="i")
plot(1, type="l" , xlab="", ylab="", col="blue", lwd=2)
legend("topleft",col=c("Blue"), legend =c("Función cúbica"), lwd=3, bty = "n")

Flujos2<- as.data.frame(t(read.csv("Ford-Fulkerson2.csv", header=FALSE)))
Flujos1<-as.data.frame(t(read.csv("Ford-Fulkerson2v0.csv", header=FALSE)))
Flujos2<-as.data.frame(t(read.csv("Ford-Fulkerson2v1.csv", header=FALSE)))
Flujos3<-as.data.frame(t(read.csv("Ford-Fulkerson2v2.csv", header=FALSE)))
Flujos4<-as.data.frame(t(read.csv("Ford-Fulkerson2v3.csv", header=FALSE)))
FlujoT2<-rbind(Flujos2,Flujos1,Flujos2,Flujos3,Flujos4)
colnames(FlujoT2) <- c(5:19)
shapiro.test(t(FlujoT2)) #Son normales ya que vienen de datos generados normalmente
pdf("FlujoFord2.pdf")
boxplot(FlujoT2, main="Flujo versus número de nodos", xlab=c("Número de nodos"), ylab=c("Flujo"), plot=TRUE)
par(new=TRUE, pty="s", xaxt="n", yaxt="n", xaxs="i")
plot(1, type="l" , xlab="", ylab="", col="blue", lwd=2)
legend("topleft",col=c("Blue"), legend =c("Función cúbica"), lwd=3, bty = "n")
graphics.off()